---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit)  }}"
      api_uri: "https://intersight.com/api/v1"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: present
  tasks:
  - name: Create Multicast Policy
    cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: "/fabric/MulticastPolicies"
      query_params:
        $filter: "Name eq 'Demo_Multicast'"
      api_body: {
        "Organization": {
            "ObjectType": "organization.Organization",
            "Moid": "xxxxx"
        },
        "Name": "Demo_Multicast",
        "QuerierState": "Disabled",
        "SnoopingState": "Enabled",
        "SrcIpProxy": "Enabled",
        "Tags": []
      }
